version: '3.1'
services:
  web:
    build: .
    command: node app.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports: 
      - 80:8080
    links:
      - mongo
    
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017